<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	  <ImplicitUsings>disable</ImplicitUsings>
    <Version>9.0.6</Version>
    <Authors>Builderb (Fluxpoint Development)</Authors>
    <Company>Fluxpoint Development</Company>
    <Description>A C# lib for using the Stoat Chat API and connecting to the gateway with a user or bot account.</Description>
    <Product>StoatSharp</Product>
    <PackageProjectUrl>https://docs.fluxpoint.dev/stoatsharp</PackageProjectUrl>
    <RepositoryUrl>https://github.com/FluxpointDev/StoatSharp</RepositoryUrl>
    <PackageTags>revolt, revolt bot, bot, revoltsharp, revoltchat, stoatchat, stoat, revolt c#</PackageTags>
    <PackageReleaseNotes>See changelog https://docs.fluxpoint.dev/stoatsharp/changelog</PackageReleaseNotes>
    <Nullable>enable</Nullable>
    <PackageIcon>PackageIcon.png</PackageIcon>

    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>StoatSharp.xml</DocumentationFile>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="PackageIcon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
